AWSTemplateFormatVersion: "2010-09-09"
Description: "AWS CloudFormation template for Jalad E Seva UI"
Transform: "AWS::Serverless-2016-10-31"
Parameters:
  # SSLCertArn:
  #   Description: "ACM Cert arn for *.example.com"
  #   Type: "String"
  # Hostname:
  #   Description: "Hostname in DNS for ui"
  #   Type: "String"
  BucketName:
    Description: "UI Bucket Asset"
    Type: "String"
  Env:
    Description: "Environment for the deployment"
    Type: "String"
    Default: "dev"
  ProjectName:
    Description: "Project Name"
    Type: "String"
    Default: "jalad"

  
Resources:
  jaladUIBucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: !Sub "${ProjectName}-${BucketName}-${Env}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        BlockPublicPolicy: false
        IgnorePublicAcls: false
        RestrictPublicBuckets: false
      WebsiteConfiguration:
        IndexDocument: "index.html"
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerPreferred
    DeletionPolicy: Retain

  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref jaladUIBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: '*'
            Action: s3:GetObject
            Resource: !Sub arn:aws:s3:::${jaladUIBucket}/*

  CloudFrontOAC:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: "ReactAppOACjalad"
        Description: "OAC for React S3 Hosting"
        SigningProtocol: "sigv4"
        SigningBehavior: "always"
        OriginAccessControlOriginType: "s3"

  ReactAppCDN:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Enabled: true
        DefaultRootObject: "index.html"
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: "http-only"
            DomainName: !Join ["", [!Ref "jaladUIBucket", ".s3-website-", !Ref "AWS::Region", ".amazonaws.com"]]
            Id: !Join ["", ["Custom-", !Ref "jaladUIBucket", ".s3-website-", !Ref "AWS::Region", ".amazonaws.com/"]]
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
            Cookies: {Forward: "none"}
            Headers: ["Origin"]
          TargetOriginId: !Join ["", ["Custom-", !Ref "jaladUIBucket", ".s3-website-", !Ref "AWS::Region", ".amazonaws.com/"]]
          ViewerProtocolPolicy: "redirect-to-https"
        ViewerCertificate:
          CloudFrontDefaultCertificate: true
        CustomErrorResponses:
          - ErrorCode: 403
            ResponsePagePath: "/index.html"
            ResponseCode: 200
            ErrorCachingMinTTL: 0
          - ErrorCode: 404
            ResponsePagePath: "/index.html"
            ResponseCode: 200
            ErrorCachingMinTTL: 0
        PriceClass: "PriceClass_200"
        HttpVersion: "http2"

Outputs:
  S3BucketName:
    Description: "S3 bucket name for the React app"
    Value: !Ref jaladUIBucket

  CloudFrontURL:
    Description: "CloudFront distribution URL"
    Value: !Sub "https://${ReactAppCDN.DomainName}"

  CloudFrontDistributionID:
    Description: "CloudFront Distribution ID"
    Value: !Ref ReactAppCDN